export const dict = {
  en: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    or: 'or',
    password: 'Password',
    passwordConfirmation: 'Confirm password',
    passwordsDoNotMatch: 'Passwords do not match!',
    accountNotVerifiedYet: 'Account not verified yet',
    resetYourPassword: 'Existing user found. Please reset your password',
    forgotPassword: 'Forgot Password?',
    userDoesNotExist: 'User does not exist!',
    insertCode: 'Insert code',
    confirm: 'Confirm',
    resendCode: 'Resend code?',
    invalidVerificationCode: 'Invalid verification code provided, please try again.',
    usernameExistsException: 'An account with the given email already exists.',
    firstName: 'First name',
    lastName: 'Last name',
    signOut: 'Sign Out',
    done: 'Done',
    test: 'Test'
  },
  ru: {
    signIn: 'Вход',
    signUp: 'Регистрация',
    or: 'или',
    password: 'Пароль',
    passwordConfirmation: 'Подтвердить пароль',
    passwordsDoNotMatch: 'Пароли не совпадают!',
    accountNotVerifiedYet: 'Аккаунт еще не подтвержден',
    resetYourPassword: 'Найден существующий пользователь. Пожалуйста, сбросьте свой пароль',
    forgotPassword: 'Забыли пароль?',
    userDoesNotExist: 'Пользователь не существует!',
    insertCode: 'Вставьте код',
    confirm: 'Подтвердить',
    resendCode: 'Отправить код еще раз?',
    invalidVerificationCode: 'Предоставлен неверный код подтверждения, попробуйте еще раз.',
    usernameExistsException: 'Аккаунт с данным адресом электронной почты уже существует.',
    firstName: 'Имя',
    lastName: 'Фамилия',
    signOut: 'Выйти',
    done: 'Сохранить',
    test: 'Тест'
  }
}
